# 리스트 6.3  cookbook-deployment-connectionsposts.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectionsposts
  labels:
    app: connectionsposts
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: connectionsposts
    template:
      metadata:
        labels:
          app: connectionsposts
      spec:
        containers:
        - name: connectionsposts
          image: cdavisafc/cloudnative-appconfig-connectionposts:0.0.1
          env:
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
